### ISSUE TITLE
[Init] 프로젝트 초기 세팅 

### ISSUE THREAD

**Issue by pcsoyeon** [pcsoyeon/SSAC-Diary#1]
##Todo
- [x] .gitignore 파일 추가
- [x] 프로젝트 폴더링
- [x] Base 파일 추가
- [x] SPM 파일 추가
- [ ] UIFramework 추가 (선택)
- [ ] 에셋 추가 (선택)
