### ISSUE TITLE
[Feat] 일기 작성 UI 수정 및 Create 구현 

### ISSUE THREAD

**Issue by pcsoyeon** [pcsoyeon/SSAC-Diary#10]
## Todo
- [x] 일기 작성 UI 수정 
- [x] TextField 입력값을 Realm Database로 Create 구현 
- [x] 앱 플로우 수정 (일기 리스트 > 일기 추가 > 사진 검색/사진 갤러리에서 갖고오기)
