### ISSUE TITLE
[Feat] 파일매니저로 이미지 파일 관리

### ISSUE THREAD

**Issue by pcsoyeon** [pcsoyeon/SSAC-Diary#12]
## Todo
- [ ] 파일 매니저로 이미지 파일 저장
- [ ] 이미지 파일 읽기
- [ ] 이미지 파일 삭제
