### ISSUE TITLE
[Network] 이미지 검색 API 연결 

### ISSUE THREAD

**Issue by pcsoyeon** [pcsoyeon/SSAC-Diary#4]
## Todo
- [x] 네트워크 Key 파일 추가
- [x] .gitignore 추가
- [x] 네트워크 Base 파일 (EndPoint, NetworkError, URL 관련) 추가
- [x] 이미지 검색 API 연결 
- [x] 서버 응답 데이터 > UI
