### ISSUE TITLE
[Feat] Realm Database 구축 

### ISSUE THREAD

**Issue by pcsoyeon** [pcsoyeon/SSAC-Diary#7]
## Todo
- [x] Realm SPM 추가
- [x] 테이블 구조 생성 
- [x] 일기 저장 기능 구현
- [x] 일기 저장 후 불러오기 
- [x] UI/플로우 수정
